services:
  postgres:
    image: postgres:15
    container_name: devbank_db
    restart: always
    environment:
      POSTGRES_USER: devbank
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: devbank
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
