services:
  postgres:
    image: postgres
    container_name: "devbank_db"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbank
    ports:
      - "5433:5433"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
